[package]
name = "gitvote"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
askama = "0.11.1"
axum = "0.5.6"
clap = { version = "3.1.18", features = ["derive"] }
config = "0.13.1"
deadpool-postgres = { version = "0.10.2", features = ["serde"] }
hex = "0.4.3"
hmac = "0.12.1"
humantime = "2.1.0"
humantime-serde = "1.1.1"
jsonwebtoken = "8.1.0"
octocrab = "0.16.0"
openssl = { version = "0.10.40", features = ["vendored"] }
postgres-openssl = "0.5.0"
reqwest = "0.11.10"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
sha2 = "0.10.2"
tokio = {version = "1.18.2", features = ["macros", "rt-multi-thread", "signal"] }
tokio-postgres = { version = "0.7.6", features = ["with-uuid-1", "with-serde_json-1", "with-time-0_3"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["trace"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
